server:
  address: 0.0.0.0
spring:
  config:
    import:
      optional:file:.env[.properties]
  application:
    name: p2chat-backend
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use "update" only for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect